const hanabomCategory = [
  {
    id: 56,
    name: "Accessories",
    slug: "accessories",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 1,
    count: 108,
    _links: { self: [Array], collection: [Array] },
    options: ["Acc", "Accessories"],
  },
  {
    id: 258,
    name: "BAGS",
    slug: "bags",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 4,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 245,
    name: "BLOUSES",
    slug: "women-blouses",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 18,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 53,
    name: "Bottoms",
    slug: "bottoms",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 6,
    count: 79,
    _links: { self: [Array], collection: [Array] },
    options: ["BOTTOMS", "Bottom"],
  },
  {
    id: 233,
    name: "BOTTOMS",
    slug: "women-bottoms",
    parent: 229,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 79,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["BOTTOMS"],
  },
  {
    id: 270,
    name: "BOTTOMS",
    slug: "men-bottoms",
    parent: 55,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 1,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["BOTTOMS FOR MEN", "BOTTOMS"],
  },
  {
    id: 59,
    name: "Cardigans",
    slug: "cardigans",
    parent: 51,
    description: "",
    display: "default",
    image: null,
    menu_order: 16,
    count: 32,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["CARDIGAN", "CARDIGANS"],
  },
  {
    id: 236,
    name: "CARDIGANS",
    slug: "women-cardigans",
    parent: 231,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 29,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["CARDIGAN", "CARDIGANS"],
  },
  {
    id: 256,
    name: "Cardigans",
    slug: "men-cardigans",
    parent: 242,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 3,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["CARDIGAN", "CARDIGANS"],
  },
  {
    id: 61,
    name: "Coats",
    slug: "coats",
    parent: 51,
    description: "",
    display: "default",
    image: null,
    menu_order: 17,
    count: 2,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Coat", "Coats"],
  },
  {
    id: 237,
    name: "COATS",
    slug: "women-coats",
    parent: 231,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 2,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Coat", "Coats"],
  },
  {
    id: 261,
    name: "Coats",
    slug: "men-coats",
    parent: 242,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 0,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Coat", "Coats"],
  },
  {
    id: 54,
    name: "Dresses",
    slug: "dresses",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 11,
    count: 39,
    _links: { self: [Array], collection: [Array] },
    options: ["Dress", "Dresses"],
  },
  {
    id: 234,
    name: "DRESSES",
    slug: "women-dresses",
    parent: 229,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 23,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Dress", "Dresses"],
  },
  {
    id: 225,
    name: "Fall",
    slug: "fall",
    parent: 222,
    description: "",
    display: "default",
    image: null,
    menu_order: 22,
    count: 85,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["F/w"],
  },
  {
    id: 254,
    name: "FALL/WINTER",
    slug: "pjs-fall-winter",
    parent: 253,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 1,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["F/w", "FALL/WINTER"],
  },
  {
    id: 139,
    name: "Fast-Delivery",
    slug: "fast-delivery",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 12,
    count: 288,
    _links: { self: [Array], collection: [Array] },
    options: [],
  },
  {
    id: 260,
    name: "HAIR ACC",
    slug: "hair-accessories",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 11,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 227,
    name: "Hair Accessory",
    slug: "hair_acc",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 2,
    count: 7,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 259,
    name: "HAT",
    slug: "hat",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 14,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 246,
    name: "HOODIES",
    slug: "women-hoodies",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 8,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Hoodies And Sweatshirts"],
  },
  {
    id: 268,
    name: "Hoodies",
    slug: "men-hoodies",
    parent: 263,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 4,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Hoodies And Sweatshirts"],
  },
  {
    id: 62,
    name: "Hoodies &amp; Sweatshirts",
    slug: "hoodies-sweatshirts",
    parent: 52,
    description: "",
    display: "default",
    image: null,
    menu_order: 28,
    count: 23,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Hoodies And Sweatshirts"],
  },
  {
    id: 137,
    name: "Jacket",
    slug: "jacket",
    parent: 51,
    description: "",
    display: "default",
    image: null,
    menu_order: 18,
    count: 23,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jacket"],
  },
  {
    id: 238,
    name: "JACKETS",
    slug: "women-jackets",
    parent: 231,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 14,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jacket"],
  },
  {
    id: 262,
    name: "Jackets",
    slug: "men-jackets",
    parent: 242,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 1,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jacket"],
  },
  {
    id: 69,
    name: "Jeans",
    slug: "jeans",
    parent: 53,
    description: "",
    display: "default",
    image: null,
    menu_order: 7,
    count: 18,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jeans", "Jean"],
  },
  {
    id: 248,
    name: "JEANS",
    slug: "women-jeans",
    parent: 233,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 16,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jeans", "Jean"],
  },
  {
    id: 271,
    name: "Jeans",
    slug: "men-jeans",
    parent: 270,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 0,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jeans", "Jean"],
  },
  {
    id: 74,
    name: "Jewelry",
    slug: "jewelry",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 3,
    count: 23,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Jewelry"],
  },
  {
    id: 65,
    name: "Knitwears",
    slug: "knitwears",
    parent: 52,
    description: "",
    display: "default",
    image: null,
    menu_order: 29,
    count: 52,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Knitwears", "Knitwear"],
  },
  {
    id: 240,
    name: "KNITWEARS",
    slug: "women-knitwears",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 26,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Knitwears", "Knitwear"],
  },
  {
    id: 265,
    name: "Knitwears",
    slug: "men-knitwears",
    parent: 263,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 2,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Knitwears", "Knitwear"],
  },
  {
    id: 55,
    name: "Men",
    slug: "men",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 13,
    count: 24,
    _links: { self: [Array], collection: [Array] },
    options: ["MEN", "Unisex"],
  },
  {
    id: 50,
    name: "New",
    slug: "new",
    parent: 0,
    description: "Newly uploaded items.\r\n5% discount on every new items!",
    display: "products",
    image: null,
    menu_order: 14,
    count: 123,
    _links: { self: [Array], collection: [Array] },
    options: ["NEW"],
  },
  {
    id: 75,
    name: "Other",
    slug: "other-accessories",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 5,
    count: 27,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["other accesories"],
  },
  {
    id: 51,
    name: "Outer",
    slug: "outer",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 15,
    count: 57,
    _links: { self: [Array], collection: [Array] },
    options: ["outer"],
  },
  {
    id: 231,
    name: "Outer",
    slug: "women-outer",
    parent: 229,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 44,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["outer"],
  },
  {
    id: 242,
    name: "OUTER",
    slug: "men-outer",
    parent: 55,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 4,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["OUTER FOR MEN", "outer"],
  },
  {
    id: 68,
    name: "Pants",
    slug: "pants",
    parent: 53,
    description: "",
    display: "default",
    image: null,
    menu_order: 8,
    count: 22,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["other pants"],
  },
  {
    id: 249,
    name: "PANTS",
    slug: "women-pants",
    parent: 233,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 24,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["other pants"],
  },
  {
    id: 272,
    name: "Pants",
    slug: "men-pants",
    parent: 270,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 1,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["other pants"],
  },
  {
    id: 253,
    name: "PJs",
    slug: "pjs",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 3,
    _links: { self: [Array], collection: [Array] },
    options: ["PJs"],
  },
  {
    id: 140,
    name: "Pre-order",
    slug: "pre-order",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 19,
    count: 32,
    _links: { self: [Array], collection: [Array] },
    options: ["Pre-order"],
  },
  {
    id: 135,
    name: "Sale",
    slug: "sale",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 20,
    count: 2,
    _links: { self: [Array], collection: [Array] },
    options: [],
  },
  {
    id: 222,
    name: "Season",
    slug: "seaon",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 21,
    count: 195,
    _links: { self: [Array], collection: [Array] },
    options: [],
  },
  {
    id: 58,
    name: "Sets",
    slug: "sets",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 26,
    count: 23,
    _links: { self: [Array], collection: [Array] },
    options: ["Set"],
  },
  {
    id: 235,
    name: "SETS",
    slug: "women-sets",
    parent: 229,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 14,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Set"],
  },
  {
    id: 244,
    name: "SHIRTS",
    slug: "women-shirts",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 11,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Shirts and Blouses"],
  },
  {
    id: 267,
    name: "Shirts",
    slug: "men-shirts",
    parent: 263,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 1,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Shirts and Blouses"],
  },
  {
    id: 64,
    name: "Shirts &amp; Blouses",
    slug: "shirts-blouses",
    parent: 52,
    description: "",
    display: "default",
    image: null,
    menu_order: 30,
    count: 28,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Shirts and Blouses"],
  },
  {
    id: 257,
    name: "SHOES",
    slug: "shoes",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 22,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Shoes & bags"],
  },
  {
    id: 73,
    name: "Shoes &amp; Bags",
    slug: "shoes-bags",
    parent: 56,
    description: "",
    display: "default",
    image: null,
    menu_order: 4,
    count: 26,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Shoes & bags"],
  },
  {
    id: 146,
    name: "Shorts",
    slug: "shorts",
    parent: 53,
    description: "",
    display: "default",
    image: null,
    menu_order: 9,
    count: 6,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["shorts", "short"],
  },
  {
    id: 251,
    name: "SHORTS",
    slug: "women-shorts",
    parent: 233,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 9,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["shorts", "short"],
  },
  {
    id: 273,
    name: "Shorts",
    slug: "men-shorts",
    parent: 270,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 1,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["shorts", "short"],
  },
  {
    id: 67,
    name: "Skirts",
    slug: "skirts",
    parent: 53,
    description: "",
    display: "default",
    image: null,
    menu_order: 10,
    count: 37,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Skirts (n)", "Skirts", "Skirt"],
  },
  {
    id: 250,
    name: "SKIRTS",
    slug: "women-skirts",
    parent: 233,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 38,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 252,
    name: "SKORTS",
    slug: "women-skorts",
    parent: 233,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 3,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: [],
  },
  {
    id: 224,
    name: "Spring",
    slug: "spring",
    parent: 222,
    description: "",
    display: "default",
    image: null,
    menu_order: 23,
    count: 124,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["S/s"],
  },
  {
    id: 255,
    name: "SPRING/SUMMER",
    slug: "pjs-spring-summer",
    parent: 253,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 3,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["S/s", "SPRING/SUMMER"],
  },
  {
    id: 223,
    name: "Summer",
    slug: "summer",
    parent: 222,
    description: "",
    display: "default",
    image: null,
    menu_order: 24,
    count: 122,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["S/s"],
  },
  {
    id: 247,
    name: "SWEATSHIRTS",
    slug: "women-sweatshirts",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 9,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Sweatshirts"],
  },
  {
    id: 269,
    name: "Sweatshirts",
    slug: "men-sweatshirts",
    parent: 263,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 7,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Sweatshirts"],
  },
  {
    id: 239,
    name: "T-SHIRTS",
    slug: "women-t-shirts",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 43,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Tshirts"],
  },
  {
    id: 264,
    name: "T-shirts",
    slug: "men-tshirts",
    parent: 263,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 2,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Tshirts"],
  },
  {
    id: 63,
    name: "T-Shirts &amp; Tank Tops",
    slug: "t-shirts-tank-tops",
    parent: 52,
    description: "",
    display: "default",
    image: null,
    menu_order: 31,
    count: 71,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Tshirts and tank top", "Tshirts"],
  },
  {
    id: 241,
    name: "TANK TOPS",
    slug: "women-tanktops",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 17,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Tshirts and tank top"],
  },
  {
    id: 52,
    name: "Tops",
    slug: "tops",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 27,
    count: 169,
    _links: { self: [Array], collection: [Array] },
    options: ["Top", "Tops", "TOP FOR MEN"],
  },
  {
    id: 232,
    name: "TOPS",
    slug: "women-tops",
    parent: 229,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 112,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["Top", "Tops"],
  },
  {
    id: 263,
    name: "TOPS",
    slug: "men-tops",
    parent: 55,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 14,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["TOP FOR MEN", "Top", "Tops"],
  },
  {
    id: 66,
    name: "Vests",
    slug: "vests",
    parent: 52,
    description: "",
    display: "default",
    image: null,
    menu_order: 32,
    count: 9,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["vest", "vests"],
  },
  {
    id: 243,
    name: "VESTS",
    slug: "women-vests",
    parent: 232,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 6,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["vest", "vests"],
  },
  {
    id: 266,
    name: "Vests",
    slug: "men-vests",
    parent: 263,
    description: "",
    display: "default",
    image: null,
    menu_order: 0,
    count: 0,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["vest", "vests"],
  },
  {
    id: 226,
    name: "Winter",
    slug: "winter",
    parent: 222,
    description: "",
    display: "default",
    image: null,
    menu_order: 25,
    count: 48,
    _links: { self: [Array], collection: [Array], up: [Array] },
    options: ["F/w"],
  },
  {
    id: 229,
    name: "Women",
    slug: "women",
    parent: 0,
    description: "",
    display: "default",
    image: null,
    menu_order: 33,
    count: 239,
    _links: { self: [Array], collection: [Array] },
    options: ["Unisex"],
  },
];

const categoryIdFinder = (name) => {
  const result = hanabomCategory.filter((category) =>
    category.options.includes(name)
  );
  return result;
};

module.exports = { categoryIdFinder };
