name: Deploy to lambda

on:
  push:
    branches:
    - main

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "config.js"
          FILE_DATA: "module.exports = { hanabomKey : '${{ secrets.Hanabom_KEY }}', hanabomSecret : '${{ secrets.Hanabom_SECRET }}',
          dbHost : '${{ secrets.dbHost }}',
          dbPort : '${{ secrets.dbPort }}',
          dbUser : '${{ secrets.dbUser }}',
          dbPassword : '${{ secrets.dbPassword }}',
           };"
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: appleboy/lambda-action@v0.0.4
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: wix-webhooks-updation
          zip_file: bundle.zip